// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID         uuid.UUID        `json:"id"`
	ProductID  uuid.UUID        `json:"productId"`
	Quantity   int32            `json:"quantity"`
	LocationID int64            `json:"locationId"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	DeletedAt  pgtype.Timestamp `json:"deletedAt"`
}

type Location struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type Product struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Price     float64          `json:"price"`
	Quantity  *int32           `json:"quantity"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
	StoreID   uuid.UUID        `json:"storeId"`
}

type Store struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
}
