// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getStoreByUUID = `-- name: GetStoreByUUID :one
SELECT id, name FROM store
WHERE id = $1
`

func (q *Queries) GetStoreByUUID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByUUID, id)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertNewStore = `-- name: InsertNewStore :one
INSERT INTO store (
    id, name
) VALUES (
    $1, $2
) RETURNING id, name
`

func (q *Queries) InsertNewStore(ctx context.Context, iD uuid.UUID, name string) (Store, error) {
	row := q.db.QueryRow(ctx, insertNewStore, iD, name)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
